<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="5" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-17T12:50:53 IST" name="Ecommerce Application" finished-at="2023-07-17T12:53:52 IST" duration-ms="178755">
    <groups>
      <group name="Purchase">
        <method signature="PlaceOrderFlow.orderPlaceComplete(java.util.HashMap)[pri:0, instance:rahualshetty.tests.PlaceOrderFlow@95e33cc]" name="orderPlaceComplete" class="rahualshetty.tests.PlaceOrderFlow"/>
      </group> <!-- Purchase -->
      <group name="ErrorValidationGroup">
        <method signature="ErrorValidation.loginErrorValidation()[pri:0, instance:rahualshetty.tests.ErrorValidation@6c4980d3]" name="loginErrorValidation" class="rahualshetty.tests.ErrorValidation"/>
      </group> <!-- ErrorValidationGroup -->
    </groups>
    <test started-at="2023-07-17T12:50:53 IST" name="Complete Place Order Flow" finished-at="2023-07-17T12:53:27 IST" duration-ms="154008">
      <class name="rahualshetty.tests.PlaceOrderFlow">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahualshetty.tests.PlaceOrderFlow@95e33cc]" started-at="2023-07-17T12:50:59 IST" name="launchApplication" finished-at="2023-07-17T12:51:56 IST" duration-ms="57192" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderPlaceComplete(java.util.HashMap)[pri:0, instance:rahualshetty.tests.PlaceOrderFlow@95e33cc]" started-at="2023-07-17T12:51:56 IST" name="orderPlaceComplete" data-provider="userData" finished-at="2023-07-17T12:52:19 IST" duration-ms="22717" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Javed@1234, product=IPHONE 13 PRO, email=sparrow@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderPlaceComplete -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahualshetty.tests.PlaceOrderFlow@95e33cc]" started-at="2023-07-17T12:52:19 IST" name="tearDown" finished-at="2023-07-17T12:52:32 IST" duration-ms="12747" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahualshetty.tests.PlaceOrderFlow@95e33cc]" started-at="2023-07-17T12:52:32 IST" name="launchApplication" finished-at="2023-07-17T12:52:49 IST" duration-ms="17016" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderPlaceComplete(java.util.HashMap)[pri:0, instance:rahualshetty.tests.PlaceOrderFlow@95e33cc]" started-at="2023-07-17T12:52:49 IST" name="orderPlaceComplete" data-provider="userData" finished-at="2023-07-17T12:53:06 IST" duration-ms="17404" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Javed@1234, product=ZARA COAT 3, email=Pirates@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderPlaceComplete -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahualshetty.tests.PlaceOrderFlow@95e33cc]" started-at="2023-07-17T12:53:06 IST" name="tearDown" finished-at="2023-07-17T12:53:10 IST" duration-ms="3813" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahualshetty.tests.PlaceOrderFlow@95e33cc]" started-at="2023-07-17T12:53:10 IST" name="launchApplication" finished-at="2023-07-17T12:53:21 IST" duration-ms="11489" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderHistory()[pri:0, instance:rahualshetty.tests.PlaceOrderFlow@95e33cc]" started-at="2023-07-17T12:53:21 IST" name="orderHistory" finished-at="2023-07-17T12:53:26 IST" depends-on-methods="rahualshetty.tests.PlaceOrderFlow.orderPlaceComplete" duration-ms="4405" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistory -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahualshetty.tests.PlaceOrderFlow@95e33cc]" started-at="2023-07-17T12:53:26 IST" name="tearDown" finished-at="2023-07-17T12:53:27 IST" duration-ms="1454" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- rahualshetty.tests.PlaceOrderFlow -->
    </test> <!-- Complete Place Order Flow -->
    <test started-at="2023-07-17T12:53:31 IST" name="Login Error validation Flow" finished-at="2023-07-17T12:53:52 IST" duration-ms="20528">
      <class name="rahualshetty.tests.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahualshetty.tests.ErrorValidation@6c4980d3]" started-at="2023-07-17T12:53:31 IST" name="launchApplication" finished-at="2023-07-17T12:53:39 IST" duration-ms="7411" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:rahualshetty.tests.ErrorValidation@6c4980d3]" started-at="2023-07-17T12:53:39 IST" name="loginErrorValidation" finished-at="2023-07-17T12:53:40 IST" duration-ms="940" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email orpassword.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email orpassword.]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at rahualshetty.tests.ErrorValidation.loginErrorValidation(ErrorValidation.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahualshetty.tests.ErrorValidation@6c4980d3]" started-at="2023-07-17T12:53:40 IST" name="tearDown" finished-at="2023-07-17T12:53:40 IST" duration-ms="341" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:rahualshetty.tests.ErrorValidation@6c4980d3]" started-at="2023-07-17T12:53:40 IST" name="launchApplication" finished-at="2023-07-17T12:53:49 IST" duration-ms="9097" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:rahualshetty.tests.ErrorValidation@6c4980d3]" started-at="2023-07-17T12:53:49 IST" name="loginErrorValidation" finished-at="2023-07-17T12:53:50 IST" duration-ms="1187" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email orpassword.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email orpassword.]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at rahualshetty.tests.ErrorValidation.loginErrorValidation(ErrorValidation.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:rahualshetty.tests.ErrorValidation@6c4980d3]" started-at="2023-07-17T12:53:51 IST" name="tearDown" finished-at="2023-07-17T12:53:52 IST" duration-ms="513" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- rahualshetty.tests.ErrorValidation -->
    </test> <!-- Login Error validation Flow -->
  </suite> <!-- Ecommerce Application -->
</testng-results>
